Name: Ketki Gaikwad

Roll no.: 23102A0060

Branch / Div: BE CMPN A

NPTEL_WEEK_5

**Missing Data**

In [1]:
x = NA
is.na(x)

[1] TRUE

In [2]:
x = c(11, NA, 13, NA)
is.na(x)

[1] FALSE  TRUE FALSE  TRUE

In [3]:
mean(x)

[1] NA

In [4]:
mean(x, na.rm = TRUE)

[1] 12

**Missing data: Location of missing values**

In [6]:
which(is.na(x))

[1] 2 4

**Missing Data**

In [7]:
sum(is.na(x))

[1] 2

**Missing Data: Finding complete cases**

In [8]:
complete.cases(x)

[1]  TRUE FALSE  TRUE FALSE

**Missing Data: Finding complete cases**

In [10]:
x = c(11, NA, 13, NA)
x

[1] 11 NA 13 NA

In [11]:
y = na.omit(x)
y

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

**Missing data: Finding complete data set**

In [22]:
attr(y,"na.action")

[1] 2 4
attr(,"class")
[1] "omit"

**Missing data: Handling values**

In [24]:
mean(x)

[1] NA

In [25]:
mean(y)

[1] 12

**Control structures in R**

**if()**

In [26]:
x = 5
if(x > 4) x * 3

[1] 15

In [27]:
x = 3
if(x > 4) x * 3

In [28]:
x = 5
if(x > 4) {x * 3}

[1] 15

In [29]:
x = 3
if(x > 4) {x * 3}

In [30]:
x = 6
if(x > 3){
  print("The value is more than 3")
}

[1] "The value is more than 3"

In [31]:
x = 2
if(x > 3){
  print("The value is more than 3")
}

**if else()**

In [32]:
x = 5
if (x == 3) {x = x - 1} else {x = 2 * x}
x

[1] 10

In [34]:
x = 3
if (x == 3) {x = x - 1} else {x = 2 * x}
x

[1] 2

In [35]:
x = 6
if(x > 3){
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}

[1] "The value is more than 3"

In [36]:
x = 2
if(x > 3){
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}

[1] "The value is less than 3"

**if else if()**

In [37]:
x = 5
if(x == 3){
  x = x - 1;
} else if(x < 3){
  x = x + 5
} else {
  x = 2 * x
}
x

[1] 10

In [38]:
x = 3
if(x == 3){
  x = x - 1;
} else if(x < 3){
  x = x + 5
} else {
  x = 2 * x
}
x

[1] 2

**ifelse()**

In [39]:
x = 1:10
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [40]:
ifelse(x < 6, x ^ 2, x + 1)

 [1]  1  4  9 16 25  7  8  9 10 11

In [41]:
x = c(7, 9, 8, 4)
ifelse(x %% 2 == 0, "even number", "odd number")

[1] "odd number"  "odd number"  "even number" "even number"

**switch()**

In [42]:
switch(2, "apple", "banana", "orange")

[1] "banana"

In [43]:
switch(1, "apple", "banana", "orange")

[1] "apple"

In [44]:
switch("colour", "colour" = "blue", "gender" = "male", "valume" = 50)

[1] "blue"

In [46]:
switch("volume", "colour" = "blue", "gender" = "male", "volume" = 50)

[1] 50

In [47]:
switch(4, "apple", "banana", "orange")

In [48]:
switch("size", "colour" = "blue", "gender" = "male", "volume" = 50)

**which()**

In [49]:
x = c(10, 15, 8, 14, 6, 12)
x

[1] 10 15  8 14  6 12

In [50]:
which(x == 14)

[1] 4

In [51]:
which(x != 12)

[1] 1 2 3 4 5

In [52]:
which(x > 10)

[1] 2 4 6

In [54]:
x = matrix(nrow = 3, ncol = 3, data = 1:9)
x

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

In [57]:
which.min(x)
which.max(x)
which(x %% 2 == 1)
which(x %% 2 == 1, arr.ind = TRUE)

[1] 1

[1] 9

[1] 1 3 5 7 9

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3